force-app/main/default/objects/MiningSite__c/MiningSite__c.object-meta.xml
<CustomObject>
    <!--actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Mining_Site_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
    </actionOverrides>
    <description>Mining location with known ore and estimated amounts.</description>
    <label>Mining Site</label>
    <nameField>
        <label>Mining Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mining Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MiningSite__c/fields/Carbon_Footprint__c.field-meta.xml
<CustomField>
    <fullName>Carbon_Footprint__c</fullName>
    <label>Carbon Footprint (tons)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CarbonFootprintChartApex.cls
public without sharing class CarbonFootprintChartApex {
    
    @AuraEnabled
    public static list<CarbonFootprintWrapper> getMineData() {
        list<CarbonFootprintWrapper> carbonfootprints = new List<CarbonFootprintWrapper>();

        list<MiningSite__c> MineData = [SELECT Name, Carbon_Footprint__c FROM MiningSite__c WHERE Active__c = true];
        for (MiningSite__c mine : MineData) {
            carbonfootprints.add(new CarbonFootprintWrapper(mine.Name, mine.Carbon_Footprint__c));
        }
        
        return carbonfootprints;
    }
	public without sharing class CarbonFootprintWrapper {
    	@AuraEnabled public String Name { get; set; }
    	@AuraEnabled public Decimal Carbon_Footprint { get; set; }
    
    	public CarbonFootprintWrapper(String name, Decimal CarbonFootprint) {
        	this.Name = name;
        	this.Carbon_Footprint = CarbonFootprint;
    	}    
    	public CarbonFootprintWrapper() {}
	}
}