force-app/main/default/objects/MiningSite__c/MiningSite__c.object-meta.xml
<CustomObject>
    <!--actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Mining_Site_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
    </actionOverrides>
    <description>Mining location with known ore and estimated amounts.</description>
    <label>Mining Site</label>
    <nameField>
        <label>Mining Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mining Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MiningSite__c/fields/Ore__c.field-meta.xml
<CustomField>
    <fullName>Ore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ore that this site has</description>
    <label>Primary Ore</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Mining Sites</relationshipLabel>
    <relationshipName>MiningSites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AuraHomeController.cls
public class AuraHomeController {
    
	public static List<MiningSite__c> top3 = [SELECT Location__c, Name, Ore__r.Name FROM MiningSite__c ORDER BY EstimatedWorth__c DESC LIMIT 3];
    
    @AuraEnabled
    public static String imageUrlBase(Integer idx){
        if(idx > 2){
            idx = Integer.valueof(Math.random() * 2);
        }  
        if(idx < 0){
            idx = Integer.valueof(Math.random() * 2);
        }
        
        String base = 'https://image.maps.ls.hereapi.com/mia/1.6/mapview?';
        String zoomAndKey = '&z=11&apiKey=NeXaL6Ng_elBhreu8qmyiHjR6SfHo1haBFZev6507Rc';
        
        Location loc = top3[idx].Location__c;
        
        String lat = String.valueOf(loc.latitude);
        String lon = String.valueOf(loc.longitude);
        
		String url = base + 'c=' + lat + '%2C' + lon + zoomAndKey;
        return url;
    }
    
    @AuraEnabled
    public static String SiteName(Integer idx){
        if(idx > 2){
            idx = Integer.valueof(Math.random() * 2);
        }  
        if(idx < 0){
            idx = Integer.valueof(Math.random() * 2);
        }
        return top3[idx].Name;
    }
    
    @AuraEnabled
    public static String SiteOre(Integer idx){
        if(idx > 2){
            idx = Integer.valueof(Math.random() * 2);
        }  
        if(idx < 0){
            idx = Integer.valueof(Math.random() * 2);
        }
        return top3[idx].Ore__r.Name;
    }
}