force-app/main/default/objects/MiningSite__c/MiningSite__c.object-meta.xml
<CustomObject>
    <!--actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Mining_Site_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
    </actionOverrides>
    <description>Mining location with known ore and estimated amounts.</description>
    <label>Mining Site</label>
    <nameField>
        <label>Mining Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mining Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MiningSite__c/fields/Carbon_Footprint__c.field-meta.xml
<CustomField>
    <fullName>Carbon_Footprint__c</fullName>
    <label>Carbon Footprint (tons)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MiningSiteTest.cls
@isTest
public class MiningSiteTest {
    
    @testSetup
    public static void setupTests(){
        List<MiningSite__c> testSites = new List<MiningSite__c>();
        for(Integer num = 0; num < 10; num++) {
            testSites.add(new MiningSite__c(name = 'Test Site ' + num, Carbon_Footprint__c = num));
        }
        Insert testSites;
    }
    
    @isTest
    public static void TP_searchSite(){
        Test.startTest();
        MiningSiteServerController.getMiningSite('Test Site 1');
        Test.stopTest();
    }
    
    @isTest
    public static void TP_showPillars(){
        Test.startTest();
        PillarPieChartApex.getChartData();
        Test.stopTest();
    }
    
    @isTest
    public static void TP_carbonChart(){
        Test.startTest();
        CarbonFootprintChartApex.getMineData();
        CarbonFootprintChartApex.CarbonFootprintWrapper wrapper = new CarbonFootprintChartApex.CarbonFootprintWrapper();
    	wrapper.Name = 'Test Site 1';
        wrapper.Carbon_Footprint = 1;
        Test.stopTest();
    }
}